POST
http://localhost:8080/graphql

Content-Type: application/json

{
"query":"query { allBooks {id, title, numPages, theme {themeName}} }"
}

%%%

# Duration: 16 ms
# URL: http://localhost:8080/graphql

# HTTP/1.1 415

@Accept: application/json
@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Sun, 30 Jan 2022 04:53:01 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "timestamp": "2022-01-30T04:53:01.037+00:00",
  "status": 415,
  "error": "Unsupported Media Type",
  "path": "/graphql"
}